language: python

python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"

env:
  - DJANGO_VERSION=1.5
  - DJANGO_VERSION=1.6
  - DJANGO_VERSION=1.7
  - DJANGO_VERSION=dev

matrix:
  allow_failures:
    - env: DJANGO_VERSION=dev
  exclude:
    - env: DJANGO_VERSION=dev
      python: "2.6"
    - env: DJANGO_VERSION=1.7
      python: "2.6"

# command to install dependencies
install:
    - pip install tox
    - python setup.py install

# command to run tests
script:
    - tox -e py${TRAVIS_PYTHON_VERSION/./}-${DJANGO_VERSION}
